import uuid
from sqlalchemy import Column, String, Integer, Float, Text, DateTime, ForeignKey, func, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from geoalchemy2 import Geometry

from backend.app.db.base import Base


class RelocationSite(Base):
    """
    Evaluated safe candidate parcels for habitation relocation outside hazard zones.
    """
    __tablename__ = "relocation_sites"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    name = Column(String(255), nullable=False, index=True)
    available_area = Column(Float, nullable=False)           # In square meters or hectares
    current_population = Column(Integer, nullable=False, default=0)
    estimated_capacity = Column(Integer, nullable=False)     # Max carrying capacity
    available_capacity = Column(Integer, nullable=False)     # Remaining capacity buffer
    
    # Carrying capacity and multi-criteria evaluation indices (0.0 to 10.0 scale)
    water_score = Column(Float, nullable=False)              # Potable water availability
    road_access_score = Column(Float, nullable=False)        # All-weather road connectivity
    healthcare_score = Column(Float, nullable=False)         # Proximity to medical & emergency care
    hazard_score = Column(Float, nullable=False)             # Residual environmental hazard exposure (lower is safer)
    suitability_score = Column(Float, nullable=False)        # Composite multi-criteria carrying capacity score

    # PostGIS geometry: Polygon boundary of the candidate relocation site
    geometry = Column(
        Geometry(geometry_type="GEOMETRY", srid=4326, spatial_index=True),
        nullable=False
    )

    # Relationships
    recommendations = relationship(
        "RelocationRecommendation",
        back_populates="relocation_site",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    __table_args__ = (
        Index("idx_relocation_sites_capacity", "available_capacity"),
        Index("idx_relocation_sites_suitability", "suitability_score"),
    )

    def __repr__(self) -> str:
        return f"<RelocationSite(id={self.id}, name='{self.name}', capacity={self.available_capacity})>"


class RelocationRecommendation(Base):
    """
    Immediate relocation need allocations mapping vulnerable habitations to safe carrying-capacity sites.
    """
    __tablename__ = "relocation_recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    
    habitation_id = Column(
        UUID(as_uuid=True),
        ForeignKey("habitations.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    relocation_site_id = Column(
        UUID(as_uuid=True),
        ForeignKey("relocation_sites.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    priority = Column(String(20), nullable=False, index=True)  # 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'
    priority_score = Column(Float, nullable=False)             # 0.0 - 100.0 urgency score
    reason = Column(Text, nullable=False)                      # Justification generated by hazard/capacity analysis
    
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True
    )

    # Relationships
    habitation = relationship("Habitation", back_populates="recommendations")
    relocation_site = relationship("RelocationSite", back_populates="recommendations")

    __table_args__ = (
        Index("idx_recs_priority_score", "priority", "priority_score"),
    )

    def __repr__(self) -> str:
        return f"<RelocationRecommendation(id={self.id}, priority='{self.priority}', score={self.priority_score})>"
